backend:
  name: github
  branch: master
  repo: dosanj/jamiatulama-react

site_url: https://jamiatulamasolapur.netlify.app/
publish_mode: editorial_workflow
media_folder: public/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    extension: json
    files:
      - label: 'Website Content'
        name: 'website-content'
        file: 'src/content/web-content.json'
        fields:
          - label: Main Category
            name: categories
            widget: list
            fields:
              - { label: Category Name, name: english-name, widget: string }
              - label: Sub Category
                name: children
                widget: list
                fields:
                  - { label: Sub Category, name: english-name, widget: string }
                  - label: Topic List
                    name: children
                    widget: list
                    fields:
                      - {
                          label: English Name,
                          name: english-name,
                          widget: string,
                        }
                      - {
                          label: English Heading,
                          name: english-heading,
                          widget: string,
                        }
                      - {
                          label: English Sub Heading,
                          name: english-sub-heading,
                          widget: string,
                        }
                      - {
                          label: Urdu Title,
                          name: urdu-title,
                          widget: string,
                          required: false,
                        }
                      - {
                          label: Urdu Heading,
                          name: urdu-heading,
                          widget: string,
                          required: false,
                        }
                      - {
                          label: Urdu Sub Heading,
                          name: urdu-sub-heading,
                          widget: string,
                          required: false,
                        }
                      - {
                          label: Hindi Title,
                          name: hindi-title,
                          widget: string,
                          required: false,
                        }
                      - {
                          label: Hindi-Heading,
                          name: hindi-heading,
                          widget: string,
                          required: false,
                        }
                      - {
                          label: Hindi Sub Heading,
                          name: hindi-sub-heading,
                          widget: string,
                          required: false,
                        }
                      - label: Vidoes List
                        name: videos-list
                        widget: list
                        required: false
                        fields:
                          - {
                              label: Video Link,
                              name: video-url,
                              widget: string,
                            }
                          - {
                              label: English Name,
                              name: english,
                              widget: string,
                            }
                          - {
                              label: Hindi Title,
                              name: hindi,
                              widget: string,
                              required: false,
                            }
                          - {
                              label: Urdu Title,
                              name: urdu,
                              widget: string,
                              required: false,
                            }
